// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7dZVMX1qHGPAYPSp59v_9VkazOHGvKMI',
    appId: '1:639027841056:android:3e0dd627d8667cc22e1445',
    messagingSenderId: '639027841056',
    projectId: 'expense-income-tracker-f46dd',
    storageBucket: 'expense-income-tracker-f46dd.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkMsdhd9kwq9UYQ4SYKkw_lgEDV_ndSVI',
    appId: '1:639027841056:web:ab1e93e647fe826d2e1445',
    messagingSenderId: '639027841056',
    projectId: 'expense-income-tracker-f46dd',
    authDomain: 'expense-income-tracker-f46dd.firebaseapp.com',
    storageBucket: 'expense-income-tracker-f46dd.appspot.com',
    measurementId: 'G-9GGFD67EYP',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkMsdhd9kwq9UYQ4SYKkw_lgEDV_ndSVI',
    appId: '1:639027841056:web:f2bbc1f0a6b33ba42e1445',
    messagingSenderId: '639027841056',
    projectId: 'expense-income-tracker-f46dd',
    authDomain: 'expense-income-tracker-f46dd.firebaseapp.com',
    storageBucket: 'expense-income-tracker-f46dd.appspot.com',
    measurementId: 'G-Z2HB23WSV0',
  );

}